//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

@Entity
public class Menu extends AbstractLightRemoveEntity implements Serializable {

    @Basic
    private Integer sortIndex;

    @Basic
    private String name;

    @Basic
    private String link;

    @Basic
    private String icon;

    @OneToMany(targetEntity = Menu.class)
    private List<Menu> menuChilds;

    @Basic
    private String value;

    public Menu() {

    }

    public Integer getSortIndex() {
        return this.sortIndex;
    }

    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public List<Menu> getMenuChilds() {
        return this.menuChilds;
    }

    public void setMenuChilds(List<Menu> menuChilds) {
        this.menuChilds = menuChilds;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
