//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class Product extends AbstractExpirableEntity implements Serializable {

    @Basic
    private String typeProduct;

    @Basic
    private Double unit;

    @Basic
    private String name;

    @Basic
    private String typeUnit;

    @ManyToOne(targetEntity = Partner.class)
    private Partner manufacturer;

    public Product() {

    }

    public String getTypeProduct() {
        return this.typeProduct;
    }

    public void setTypeProduct(String typeProduct) {
        this.typeProduct = typeProduct;
    }

    public Double getUnit() {
        return this.unit;
    }

    public void setUnit(Double unit) {
        this.unit = unit;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTypeUnit() {
        return this.typeUnit;
    }

    public void setTypeUnit(String typeUnit) {
        this.typeUnit = typeUnit;
    }

    public Partner getManufacturer() {
        return this.manufacturer;
    }

    public void setManufacturer(Partner manufacturer) {
        this.manufacturer = manufacturer;
    }
}
