//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class AccountTransaction extends AbstractMigrableEntity implements Serializable {

    @Basic
    private BigDecimal creditTotal;

    @Basic
    private String observation;

    @Basic
    private String typeOperation;

    @Basic
    private String memo;

    @ManyToOne(targetEntity = FinancialAccount.class)
    private FinancialAccount financialAccount;

    @Basic
    private Date datePrevist;

    @Basic
    private String dateExecuted;

    @Basic
    private BigDecimal debitTotal;

    @Basic
    private String typeTransaction;

    @ManyToOne(targetEntity = Partner.class)
    private Partner partner;

    @Basic
    private BigDecimal actualBalance;

    @Basic
    private String typeMethod;

    @ManyToOne(targetEntity = Account.class)
    private Account account;

    @Basic
    private String status;

    public AccountTransaction() {

    }

    public BigDecimal getCreditTotal() {
        return this.creditTotal;
    }

    public void setCreditTotal(BigDecimal creditTotal) {
        this.creditTotal = creditTotal;
    }

    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public String getTypeOperation() {
        return this.typeOperation;
    }

    public void setTypeOperation(String typeOperation) {
        this.typeOperation = typeOperation;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public FinancialAccount getFinancialAccount() {
        return this.financialAccount;
    }

    public void setFinancialAccount(FinancialAccount financialAccount) {
        this.financialAccount = financialAccount;
    }

    public Date getDatePrevist() {
        return this.datePrevist;
    }

    public void setDatePrevist(Date datePrevist) {
        this.datePrevist = datePrevist;
    }

    public String getDateExecuted() {
        return this.dateExecuted;
    }

    public void setDateExecuted(String dateExecuted) {
        this.dateExecuted = dateExecuted;
    }

    public BigDecimal getDebitTotal() {
        return this.debitTotal;
    }

    public void setDebitTotal(BigDecimal debitTotal) {
        this.debitTotal = debitTotal;
    }

    public String getTypeTransaction() {
        return this.typeTransaction;
    }

    public void setTypeTransaction(String typeTransaction) {
        this.typeTransaction = typeTransaction;
    }

    public Partner getPartner() {
        return this.partner;
    }

    public void setPartner(Partner partner) {
        this.partner = partner;
    }

    public BigDecimal getActualBalance() {
        return this.actualBalance;
    }

    public void setActualBalance(BigDecimal actualBalance) {
        this.actualBalance = actualBalance;
    }

    public String getTypeMethod() {
        return this.typeMethod;
    }

    public void setTypeMethod(String typeMethod) {
        this.typeMethod = typeMethod;
    }

    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
