//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class InventoryItem extends AbstractEntity implements Serializable {

    @ManyToOne(targetEntity = Product.class)
    private Product product;

    @Basic
    private String quantity;

    @ManyToOne(targetEntity = Partner.class)
    private Partner supplier;

    @Basic
    private String name;

    @Basic
    private String type;

    @ManyToOne(targetEntity = Inventory.class)
    private Inventory inventory;

    public InventoryItem() {

    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public String getQuantity() {
        return this.quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public Partner getSupplier() {
        return this.supplier;
    }

    public void setSupplier(Partner supplier) {
        this.supplier = supplier;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Inventory getInventory() {
        return this.inventory;
    }

    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
}
