//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class ProductPrice extends AbstractExpirableEntity implements Serializable {

    @ManyToOne(targetEntity = Product.class)
    private Product product;

    @Basic
    private BigDecimal charge;

    @Basic
    private BigDecimal price;

    @ManyToOne(targetEntity = Inventory.class)
    private Inventory inventory;

    @Basic
    private Double percent;

    @Embedded
    @AttributeOverride(name = "value", column = @Column(name = "base_value"))
    private BigDecimal base;

    public ProductPrice() {

    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public BigDecimal getCharge() {
        return this.charge;
    }

    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Inventory getInventory() {
        return this.inventory;
    }

    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }

    public Double getPercent() {
        return this.percent;
    }

    public void setPercent(Double percent) {
        this.percent = percent;
    }

    public BigDecimal getBase() {
        return this.base;
    }

    public void setBase(BigDecimal base) {
        this.base = base;
    }
}
