//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class UserMessage extends AbstractLightRemoveEntity implements Serializable {

    @Basic
    private Date date;

    @ManyToOne(targetEntity = UserLogin.class)
    private UserLogin userFrom;

    @Basic
    private String message;

    @ManyToOne(targetEntity = UserLogin.class)
    private UserLogin userTo;

    public UserMessage() {

    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public UserLogin getUserFrom() {
        return this.userFrom;
    }

    public void setUserFrom(UserLogin userFrom) {
        this.userFrom = userFrom;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public UserLogin getUserTo() {
        return this.userTo;
    }

    public void setUserTo(UserLogin userTo) {
        this.userTo = userTo;
    }
}
